### ISSUE TITLE
asyncpg database not connecting

### ISSUE THREAD

**Issue by rosesaredumb** [Weetabicx/Toad-DiscordBot#1]
I keep getting the error when I try to connect to the database
"ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection"

Is there any way to fix this?

**Comment by Weetabicx** [comment]
Did you set up the database on your host machine?
The database you are connecting to must be hosted locally as that's what it is trying to connect to
```
#  Holds the information to connect to the logs database
bot.asyncpg_databse_connection_vars = {
    'user': 'toad',  # <-- Your database user goes here
    'password': 'discord',  # <-- Your database passowrd goes here
    'database': 'toaddb',  # <-- Your database name goes here
    'host': '127.0.0.1',  # This is the local ip which you are attempting to connect to
    'port': 5432,  # Standard port
```
